"use client"

// import type { Metadata } from "next";
import localFont from "next/font/local";
import { AppRouterCacheProvider } from '@mui/material-nextjs/v15-appRouter';
import "./globals.css";
import {
  QueryClient,
  QueryClientProvider,
} from '@tanstack/react-query'
import NavBar from "../layouts/dashboard-layout";
import { createTheme, ThemeProvider } from "@mui/material";
import { Toaster } from 'react-hot-toast';

const PoppinsRegular = localFont({
  src: "./fonts/Poppins-Regular.woff",
  variable: "--font-poppins-regular",
});

// export const metadata: Metadata = {
//   title: "Demo App",
//   description: "Generated by create next app",
// };


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const queryClient = new QueryClient()
  const theme = createTheme({
    palette: {
      mode: 'dark',
    },
  });
  return (
    <html lang="en">
      <body className={`${PoppinsRegular.variable}`}>
        <QueryClientProvider client={queryClient}>
          <AppRouterCacheProvider>
            <Toaster position="top-right" />
            <NavBar />
            <ThemeProvider theme={theme}>
              {children}
            </ThemeProvider>
          </AppRouterCacheProvider>
        </QueryClientProvider>
      </body>
    </html>
  );
}
